BEGIN;

DROP TABLE IF EXISTS event_user;
DROP TABLE IF EXISTS event_venue;
DROP TABLE IF EXISTS event_artist;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS venues;
DROP TABLE IF EXISTS artists;
DROP TABLE IF EXISTS events;
DROP TYPE IF EXISTS event_type;

COMMIT;
